# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/names.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'proto/names.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/names.proto\x12\x05names\"\xad\x02\n\tNameEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x07\x63ountry\x18\x02 \x03(\x0b\x32\x1d.names.NameEntry.CountryEntry\x12,\n\x06gender\x18\x03 \x03(\x0b\x32\x1c.names.NameEntry.GenderEntry\x12(\n\x04rank\x18\x04 \x03(\x0b\x32\x1a.names.NameEntry.RankEntry\x1a.\n\x0c\x43ountryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a-\n\x0bGenderEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a+\n\tRankEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"0\n\x0bNameDataset\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.names.NameEntry\"f\n\x13\x43ombinedNameDataset\x12\'\n\x0b\x66irst_names\x18\x01 \x01(\x0b\x32\x12.names.NameDataset\x12&\n\nlast_names\x18\x02 \x01(\x0b\x32\x12.names.NameDatasetB\x1cZ\x1ago-name-detector/pkg/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.names_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032go-name-detector/pkg/proto'
  _globals['_NAMEENTRY_COUNTRYENTRY']._loaded_options = None
  _globals['_NAMEENTRY_COUNTRYENTRY']._serialized_options = b'8\001'
  _globals['_NAMEENTRY_GENDERENTRY']._loaded_options = None
  _globals['_NAMEENTRY_GENDERENTRY']._serialized_options = b'8\001'
  _globals['_NAMEENTRY_RANKENTRY']._loaded_options = None
  _globals['_NAMEENTRY_RANKENTRY']._serialized_options = b'8\001'
  _globals['_NAMEENTRY']._serialized_start=29
  _globals['_NAMEENTRY']._serialized_end=330
  _globals['_NAMEENTRY_COUNTRYENTRY']._serialized_start=192
  _globals['_NAMEENTRY_COUNTRYENTRY']._serialized_end=238
  _globals['_NAMEENTRY_GENDERENTRY']._serialized_start=240
  _globals['_NAMEENTRY_GENDERENTRY']._serialized_end=285
  _globals['_NAMEENTRY_RANKENTRY']._serialized_start=287
  _globals['_NAMEENTRY_RANKENTRY']._serialized_end=330
  _globals['_NAMEDATASET']._serialized_start=332
  _globals['_NAMEDATASET']._serialized_end=380
  _globals['_COMBINEDNAMEDATASET']._serialized_start=382
  _globals['_COMBINEDNAMEDATASET']._serialized_end=484
# @@protoc_insertion_point(module_scope)
