// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: proto/names.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a single name entry with its metadata
type NameEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country       map[string]float32     `protobuf:"bytes,2,rep,name=country,proto3" json:"country,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // Country code → probability
	Gender        map[string]float32     `protobuf:"bytes,3,rep,name=gender,proto3" json:"gender,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`   // "M"/"F" → probability (only for first names)
	Rank          map[string]int32       `protobuf:"bytes,4,rep,name=rank,proto3" json:"rank,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`        // Country code → rank (1 = most popular)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameEntry) Reset() {
	*x = NameEntry{}
	mi := &file_proto_names_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameEntry) ProtoMessage() {}

func (x *NameEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_names_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameEntry.ProtoReflect.Descriptor instead.
func (*NameEntry) Descriptor() ([]byte, []int) {
	return file_proto_names_proto_rawDescGZIP(), []int{0}
}

func (x *NameEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NameEntry) GetCountry() map[string]float32 {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *NameEntry) GetGender() map[string]float32 {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *NameEntry) GetRank() map[string]int32 {
	if x != nil {
		return x.Rank
	}
	return nil
}

// Container for a complete name dataset (first names or last names)
type NameDataset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*NameEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameDataset) Reset() {
	*x = NameDataset{}
	mi := &file_proto_names_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameDataset) ProtoMessage() {}

func (x *NameDataset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_names_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameDataset.ProtoReflect.Descriptor instead.
func (*NameDataset) Descriptor() ([]byte, []int) {
	return file_proto_names_proto_rawDescGZIP(), []int{1}
}

func (x *NameDataset) GetEntries() []*NameEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Combined dataset with both first and last names
type CombinedNameDataset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstNames    *NameDataset           `protobuf:"bytes,1,opt,name=first_names,json=firstNames,proto3" json:"first_names,omitempty"`
	LastNames     *NameDataset           `protobuf:"bytes,2,opt,name=last_names,json=lastNames,proto3" json:"last_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombinedNameDataset) Reset() {
	*x = CombinedNameDataset{}
	mi := &file_proto_names_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedNameDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedNameDataset) ProtoMessage() {}

func (x *CombinedNameDataset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_names_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedNameDataset.ProtoReflect.Descriptor instead.
func (*CombinedNameDataset) Descriptor() ([]byte, []int) {
	return file_proto_names_proto_rawDescGZIP(), []int{2}
}

func (x *CombinedNameDataset) GetFirstNames() *NameDataset {
	if x != nil {
		return x.FirstNames
	}
	return nil
}

func (x *CombinedNameDataset) GetLastNames() *NameDataset {
	if x != nil {
		return x.LastNames
	}
	return nil
}

var File_proto_names_proto protoreflect.FileDescriptor

const file_proto_names_proto_rawDesc = "" +
	"\n" +
	"\x11proto/names.proto\x12\x05names\"\xee\x02\n" +
	"\tNameEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\acountry\x18\x02 \x03(\v2\x1d.names.NameEntry.CountryEntryR\acountry\x124\n" +
	"\x06gender\x18\x03 \x03(\v2\x1c.names.NameEntry.GenderEntryR\x06gender\x12.\n" +
	"\x04rank\x18\x04 \x03(\v2\x1a.names.NameEntry.RankEntryR\x04rank\x1a:\n" +
	"\fCountryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a9\n" +
	"\vGenderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a7\n" +
	"\tRankEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"9\n" +
	"\vNameDataset\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.names.NameEntryR\aentries\"}\n" +
	"\x13CombinedNameDataset\x123\n" +
	"\vfirst_names\x18\x01 \x01(\v2\x12.names.NameDatasetR\n" +
	"firstNames\x121\n" +
	"\n" +
	"last_names\x18\x02 \x01(\v2\x12.names.NameDatasetR\tlastNamesB\x1cZ\x1ago-name-detector/pkg/protob\x06proto3"

var (
	file_proto_names_proto_rawDescOnce sync.Once
	file_proto_names_proto_rawDescData []byte
)

func file_proto_names_proto_rawDescGZIP() []byte {
	file_proto_names_proto_rawDescOnce.Do(func() {
		file_proto_names_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_names_proto_rawDesc), len(file_proto_names_proto_rawDesc)))
	})
	return file_proto_names_proto_rawDescData
}

var file_proto_names_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_names_proto_goTypes = []any{
	(*NameEntry)(nil),           // 0: names.NameEntry
	(*NameDataset)(nil),         // 1: names.NameDataset
	(*CombinedNameDataset)(nil), // 2: names.CombinedNameDataset
	nil,                         // 3: names.NameEntry.CountryEntry
	nil,                         // 4: names.NameEntry.GenderEntry
	nil,                         // 5: names.NameEntry.RankEntry
}
var file_proto_names_proto_depIdxs = []int32{
	3, // 0: names.NameEntry.country:type_name -> names.NameEntry.CountryEntry
	4, // 1: names.NameEntry.gender:type_name -> names.NameEntry.GenderEntry
	5, // 2: names.NameEntry.rank:type_name -> names.NameEntry.RankEntry
	0, // 3: names.NameDataset.entries:type_name -> names.NameEntry
	1, // 4: names.CombinedNameDataset.first_names:type_name -> names.NameDataset
	1, // 5: names.CombinedNameDataset.last_names:type_name -> names.NameDataset
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_names_proto_init() }
func file_proto_names_proto_init() {
	if File_proto_names_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_names_proto_rawDesc), len(file_proto_names_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_names_proto_goTypes,
		DependencyIndexes: file_proto_names_proto_depIdxs,
		MessageInfos:      file_proto_names_proto_msgTypes,
	}.Build()
	File_proto_names_proto = out.File
	file_proto_names_proto_goTypes = nil
	file_proto_names_proto_depIdxs = nil
}
